platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'KPFrameworkObjC_Example' do
  pod 'KPFrameworkObjC', :path => '../'

  target 'KPFrameworkObjC_Tests' do
    inherit! :search_paths

    
  end
end
